name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: "What's Changed"
    labels:
      - 'change'
autolabeler: 
- label: 'prod-release'
  branch:
    - '/stg\/.+/'
  title:
    - '/Prod release/i'
exclude-labels:
  - 'prod-release'
change-template: '* $TITLE by @$AUTHOR in https://github.com/caffeinetv/nexus-web/pull/$NUMBER'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  $CHANGES

  **Full Changelog**: https://github.com/caffeinetv/nexus-web/compare/v$PREVIOUS_TAG...v$NEXT_PATCH_VERSION